baseurl: /
timezone: America/Los_Angeles
favicon: "img/favicon.ico"

address: 262 Meadow Pine Place, San Jose, CA 95125, USA
phone: +1.408-489-0852
email: Olga@OlgaMedia.com

collections:
- projects
- events